### PR TITLE
stable diffusion: add warning about system requirements

### PR DESCRIPTION
**Pull request by ConnorRigby**
I spent a couple days trying to get my GPU to work with Bumblebee only to find out my particular GPU doesn't have enough VRAM. This warning would have saved me a lot of time.

 
Signed-off-by: Connor Rigby <connorr@hey.com>

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks. We want to improve it but I think it represents the current state of affairs.

**Comment by jonatanklosko** [comment]
We have a note about CPU after the cell that runs the model, maybe let's move it there as well?

**Comment by ConnorRigby** [comment]
Just moved it, didn't reword tho.

**Comment by jonatanklosko** [comment]
Thanks!

**Pull request merged**
